version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8081:80"
  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www
